### ISSUE TITLE
Crash with NBS song

### ISSUE THREAD

**Issue by KosmX** [KosmX/emotes#148]
```
java.nio.BufferOverflowException
	at java.base/java.nio.Buffer.nextPutIndex(Buffer.java:721)
	at java.base/java.nio.HeapByteBuffer.put(HeapByteBuffer.java:209)
	at io.github.kosmx.emotes.common.network.EmotePacket.writeSubPacket(EmotePacket.java:104)
	at io.github.kosmx.emotes.common.network.EmotePacket.lambda$write$2(EmotePacket.java:90)
	at java.base/java.util.HashMap.forEach(HashMap.java:1425)
	at io.github.kosmx.emotes.common.network.EmotePacket.write(EmotePacket.java:88)
	at io.github.kosmx.emotes.fabric.network.ClientNetworkInstance.sendMessage(ClientNetworkInstance.java:80)
	at io.github.kosmx.emotes.main.network.ClientPacketManager.send(ClientPacketManager.java:57)
	at io.github.kosmx.emotes.main.network.ClientEmotePlay.clientStartLocalEmote(ClientEmotePlay.java:35)
	at io.github.kosmx.emotes.main.EmoteHolder.playEmote(EmoteHolder.java:210)
	at io.github.kosmx.emotes.main.EmoteHolder.playEmote(EmoteHolder.java:236)
	at io.github.kosmx.emotes.main.screen.ingame.FastMenuScreenLogic$FastMenuWidget.EmotesOnClick(FastMenuScreenLogic.java:78)
	at io.github.kosmx.emotes.main.screen.widget.AbstractFastChooseWidget.emotes_mouseClicked(AbstractFastChooseWidget.java:126)
	at io.github.kosmx.emotes.arch.gui.screen.IWidgetLogicImpl.method_25402(IWidgetLogicImpl.java:13)
	at net.minecraft.class_4069.method_25402(class_4069.java:27)
	at io.github.kosmx.emotes.arch.gui.screen.AbstractControlledModScreen.method_25402(AbstractControlledModScreen.java:136)
	at net.minecraft.class_312.method_1611(class_312.java:94)
	at net.minecraft.class_437.method_25412(class_437.java:490)
	at net.minecraft.class_312.method_1601(class_312.java:94)
	at net.minecraft.class_312.method_22686(class_312.java:165)
	at net.minecraft.class_1255.execute(class_1255.java:118)
	at net.minecraft.class_312.method_22684(class_312.java:165)
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:160)
	at net.minecraft.class_1041.method_15998(class_1041.java:454)
	at net.minecraft.class_310.method_1523(class_310.java:1137)
	at net.minecraft.class_310.method_1514(class_310.java:728)
	at net.minecraft.client.main.Main.main(Main.java:217)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:234)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:153)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)

```

**Comment by KosmX** [comment]
https://github.com/KosmX/emotes/blob/2c789d9586992234b92b77a756758b7a1462f9eb/emotesCommon/src/main/java/io/github/kosmx/emotes/common/network/EmotePacket.java#L104

**Comment by KosmX** [comment]
This issue is already fixed in the dev.
