### ISSUE TITLE
Crash {io.github.kosmx.emotes.executor.EmoteInstance.config is null}

### ISSUE THREAD

**Issue by ccyounga** [KosmX/emotes#273]
Greetings! I'm using a server like this:
Gravit launcher, build on fabric with client mods.
Server on paper 1.18.2 core.
I use bukkit version 2.1.2 plugin, client mod version 2.1.2 fabric 1.18.2.
Used an early mod version 2.1.3 build 30 1.18.2 fabric, in conjunction with plugin 2.1 SNAPSHOT build 9. Experienced the same problem as now! And I even used it on version 1.16.5 with a mod of the appropriate version and a plugin of version 2.1, there was an error too!
It started after we updated several plugins on the server: mmocore, mmoitems, mythiclib, mythicmobs. All plugins are from the same author and work together. mmocore was added as a new one, the rest just updated with a version. Everything worked fine before, the plugins were updated on version 1.16.5, then we changed the version of the game client and server to 1.18.2. The plugins themselves work without problems, however the emotecraft plugin constantly throws errors and does not synchronize animations among players.
I mentioned third-party plugins because the problems started right after they were added. However, I can't link the problem to them, as they don't affect the client-side in any way and can't cause problems for the emotecraft plugin. However, the mmocore plugin intercepts the packet to change the functionality of the F key, which initially transfers the item to the left hand, but mmocore causes this key to activate its skill, canceling the transfer to the left hand functionality.
Maybe this particular packet capture from the client is somehow related, but I'm not sure.

Actually the error itself: https://www.toptal.com/developers/hastebin/irebedofeq.md

[20:30:16 WARN]: java.lang.NullPointerException: Cannot read field "validThreshold" because "io.github.kosmx.emotes.executor.EmoteInstance.config" is null
[20:30:16 WARN]:        at emotecraft-2.1.2-bukkit.jar//io.github.kosmx.emotes.server.network.AbstractServerEmotePlay.receiveMessage(AbstractServerEmotePlay.java:75)
[20:30:16 WARN]:        at emotecraft-2.1.2-bukkit.jar//io.github.kosmx.emotes.bukkit.network.ServerSideEmotePlay.receivePluginMessage(ServerSideEmotePlay.java:43)
[20:30:16 WARN]:        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
[20:30:16 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3225)
[20:30:16 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInCustomPayload.a(PacketPlayInCustomPayload.java:37)
[20:30:16 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInCustomPayload.a(PacketPlayInCustomPayload.java:15)
[20:30:16 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[20:30:16 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[20:30:16 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[20:30:16 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[20:30:16 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1400)
[20:30:16 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[20:30:16 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[20:30:16 WARN]:        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1377)
[20:30:16 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1370)
[20:30:16 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.bo(IAsyncTaskHandler.java:114)
[20:30:16 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1504)
[20:30:16 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1226)
[20:30:16 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[20:30:16 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)

One of the helpers in the T discord channel, like Toren, saw this error several times because I contacted him in the general text channel. Perhaps he remembers. Told me to go to github.

**Comment by ccyounga** [comment]
In addition to the error that occurs above, I throw an error that manifests itself on server loading. Before that, I hadn't noticed it was there.
```
[07:41:43] [Server thread/INFO]: [emotecraft] Loading emotecraft v2.1.3-SNAPSHOT-build.32
[07:41:43] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_18_R2.CraftServer] Cannot read field "loadBuiltinEmotes" because "io.github.kosmx.emotes.executor.EmoteInstance.config" is null initializing emotecraft v2.1.3-SNAPSHOT-build.32 (Is it up to date?)
java.lang.NullPointerException: Cannot read field "loadBuiltinEmotes" because "io.github.kosmx.emotes.executor.EmoteInstance.config" is null
	at io.github.kosmx.emotes.server.serializer.UniversalEmoteSerializer.serializeInternalJson(UniversalEmoteSerializer.java:109) ~[emotecraft-2.1.3-SNAPSHOT-build.32-bukkit.jar:?]
	at io.github.kosmx.emotes.server.serializer.UniversalEmoteSerializer.loadEmotes(UniversalEmoteSerializer.java:88) ~[emotecraft-2.1.3-SNAPSHOT-build.32-bukkit.jar:?]
	at io.github.kosmx.emotes.bukkit.BukkitWrapper.onLoad(BukkitWrapper.java:42) ~[emotecraft-2.1.3-SNAPSHOT-build.32-bukkit.jar:?]
	at org.bukkit.craftbukkit.v1_18_R2.CraftServer.loadPlugins(CraftServer.java:424) ~[paper-1.18.2.jar:git-Paper-386]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:288) ~[paper-1.18.2.jar:git-Paper-386]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-386]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-386]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by KosmX** [comment]
Can you send the whole startup log?  
(I think something might missing)

**Comment by KosmX** [comment]
`.minecraft/config/emotecraft.json` (.minecraft is your server directory)  
is __empty__.  

try to delete the config, so emotecraft can generate new.  
If that isn't working, place an empty json object into it:  
```json
{}
```

I'll fix this crash in the next release

**Comment by ccyounga** [comment]
We resolved the issue by contacting discord. It consisted of empty emotecraft files in the server's config folder. It was decided by deleting these plugins so that he would generate them on a new one.
Can be closed.
