### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by RambilE** [KosmX/emotes#305]
When launching minecraft fabric with emotecraft it crashes.

1. Launch minecraft 1.19.2 fabric with emotecraft.
2. See error.

**Expected behavior**
Expected to launch minecraft.

**Minecraft version+mod loader**
 - 1.19.2
 - fabric 0.14.9
 - Client

emotecraft-for-MC1.19.2-2.2.5-fabric

log here

[18:14:20] [main/INFO]: Loading Minecraft 1.19.2 with Fabric Loader 0.14.9
[18:14:20] [main/WARN]: Mod resolution failed
[18:14:20] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE emotecraft 2.2.5 {depends fabric @ [>=0.16.4]}, ROOT_FORCELOAD_SINGLE emotecraft 2.2.5]
[18:14:20] [main/INFO]: Reason: [HARD_DEP emotecraft 2.2.5 {depends fabric @ [>=0.16.4]}]
[18:14:20] [main/INFO]: Fix: add [add:fabric 0.16.4 ([[0.16.4,?)])], remove [], replace []
[18:14:20] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, version 0.16.4 or later.
Unmet dependency listing:
	 - Mod 'Emotecraft' (emotecraft) 2.2.5 requires version 0.16.4 or later of fabric, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]

crash report here

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric, version 0.16.4 or later.
Unmet dependency listing:
	 - Mod 'Emotecraft' (emotecraft) 2.2.5 requires version 0.16.4 or later of fabric, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Additional context**

**Comment by KosmX** [comment]
Please install Fabric API
