### ISSUE TITLE
Error in console when player joins

### ISSUE THREAD

**Issue by Josh65-2201** [KosmX/emotes#334]
**Describe the bug**

**To Reproduce**
1. Join a server
2. Check console

**Expected behavior**
No warning should show

**Minecraft version + mod loader**
 - Version: 1.18.2
 - Modded: Fabric 0.14.9
 - Server

**Mod version**: [e.g. 2.1.3-fabric]
2.2.5 fabric and bucket

**Minecraft log __and__ crash report**:
```
[15:50:42 WARN]: java.lang.NullPointerException: Cannot invoke "io.github.kosmx.emotes.server.network.IServerNetworkInstance.getEmoteTracker()" because the return value of "io.github.kosmx.emotes.server.network.AbstractServerEmotePlay.getPlayerNetworkInstance(Object)" is null
[15:50:42 WARN]:        at emotecraft-2.2.5-bukkit.jar//io.github.kosmx.emotes.server.network.AbstractServerEmotePlay.playerStartTracking(AbstractServerEmotePlay.java:213)
[15:50:42 WARN]:        at emotecraft-2.2.5-bukkit.jar//io.github.kosmx.emotes.bukkit.network.BukkitNetworkInstance.presenceResponse(BukkitNetworkInstance.java:55)
[15:50:42 WARN]:        at emotecraft-2.2.5-bukkit.jar//io.github.kosmx.emotes.server.network.AbstractServerEmotePlay.receiveMessage(AbstractServerEmotePlay.java:103)
[15:50:42 WARN]:        at emotecraft-2.2.5-bukkit.jar//io.github.kosmx.emotes.server.network.AbstractServerEmotePlay.receiveMessage(AbstractServerEmotePlay.java:92)
[15:50:42 WARN]:        at emotecraft-2.2.5-bukkit.jar//io.github.kosmx.emotes.bukkit.network.ServerSideEmotePlay.receivePluginMessage(ServerSideEmotePlay.java:45)
[15:50:42 WARN]:        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
[15:50:42 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3225)
[15:50:42 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInCustomPayload.a(PacketPlayInCustomPayload.java:37)
[15:50:42 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInCustomPayload.a(PacketPlayInCustomPayload.java:15)
[15:50:42 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[15:50:42 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[15:50:42 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[15:50:42 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[15:50:42 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1400)
[15:50:42 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188)
[15:50:42 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.y(IAsyncTaskHandler.java:126)
[15:50:42 WARN]:        at net.minecraft.server.MinecraftServer.be(MinecraftServer.java:1377)
[15:50:42 WARN]:        at net.minecraft.server.MinecraftServer.y(MinecraftServer.java:1370)
[15:50:42 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.bo(IAsyncTaskHandler.java:114)
[15:50:42 WARN]:        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1504)
[15:50:42 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1226)
[15:50:42 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[15:50:42 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Additional context**

**Comment by KosmX** [comment]
If the server is a fabric server, please use the fabric version __on__ the server.
If the server is not fabric (bukkit or derivate), please describe server version and provide full server log.

**Comment by Josh65-2201** [comment]
I'm using paper 1.18.2 387 server and fabric client. And I'm using the correct version for both.
[2022-11-22-2.log](https://github.com/KosmX/emotes/files/10069110/2022-11-22-2.log)

**Comment by KosmX** [comment]
oh-no
I belive FakePlayers break the api in some point.
The issue should __not__ be a problem, but I'll try to implement a fix :)

**Comment by mirronake** [comment]
I have same issue, but other error.

1.19.3
Paper Server


```
[11:55:49 WARN]: org.bukkit.plugin.messaging.MessageTooLargeException: Attempted to send a plugin message that was too large. The maximum length a plugin message may be is 32766 bytes (tried to send one that is 48602 bytes long).
[11:55:49 WARN]:        at org.bukkit.plugin.messaging.StandardMessenger.validatePluginMessage(StandardMessenger.java:547)
[11:55:49 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.entity.CraftPlayer.sendPluginMessage(CraftPlayer.java:1996)
[11:55:49 WARN]:        at emotecraft-2.2.5-bukkit.jar//io.github.kosmx.emotes.bukkit.network.BukkitNetworkInstance.sendMessage(BukkitNetworkInstance.java:42)
[11:55:49 WARN]:        at emotecraft-2.2.5-bukkit.jar//io.github.kosmx.emotes.api.proxy.AbstractNetworkInstance.sendMessage(AbstractNetworkInstance.java:54)
[11:55:49 WARN]:        at emotecraft-2.2.5-bukkit.jar//io.github.kosmx.emotes.api.proxy.AbstractNetworkInstance.sendMessage(AbstractNetworkInstance.java:72)
[11:55:49 WARN]:        at emotecraft-2.2.5-bukkit.jar//io.github.kosmx.emotes.server.network.IServerNetworkInstance.presenceResponse(IServerNetworkInstance.java:30)
[11:55:49 WARN]:        at emotecraft-2.2.5-bukkit.jar//io.github.kosmx.emotes.bukkit.network.BukkitNetworkInstance.presenceResponse(BukkitNetworkInstance.java:52)
[11:55:49 WARN]:        at emotecraft-2.2.5-bukkit.jar//io.github.kosmx.emotes.server.network.AbstractServerEmotePlay.receiveMessage(AbstractServerEmotePlay.java:103)
[11:55:49 WARN]:        at emotecraft-2.2.5-bukkit.jar//io.github.kosmx.emotes.server.network.AbstractServerEmotePlay.receiveMessage(AbstractServerEmotePlay.java:92)
[11:55:49 WARN]:        at emotecraft-2.2.5-bukkit.jar//io.github.kosmx.emotes.bukkit.network.ServerSideEmotePlay.receivePluginMessage(ServerSideEmotePlay.java:45)
[11:55:49 WARN]:        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
[11:55:49 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3543)
[11:55:49 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInCustomPayload.a(PacketPlayInCustomPayload.java:37)
[11:55:49 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInCustomPayload.a(PacketPlayInCustomPayload.java:15)
[11:55:49 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
[11:55:49 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
[11:55:49 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
[11:55:49 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
[11:55:49 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
[11:55:49 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
[11:55:49 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
[11:55:49 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
[11:55:49 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
[11:55:49 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
[11:55:49 WARN]:        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1289)
[11:55:49 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1177)
[11:55:49 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[11:55:49 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by distribate** [comment]
> I have same issue, but other error.
> 
> 1.19.3 Paper Server
> 
> ```
> [11:55:49 WARN]: org.bukkit.plugin.messaging.MessageTooLargeException: Attempted to send a plugin message that was too large. The maximum length a plugin message may be is 32766 bytes (tried to send one that is 48602 bytes long).
> [11:55:49 WARN]:        at org.bukkit.plugin.messaging.StandardMessenger.validatePluginMessage(StandardMessenger.java:547)
> [11:55:49 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.entity.CraftPlayer.sendPluginMessage(CraftPlayer.java:1996)
> [11:55:49 WARN]:        at emotecraft-2.2.5-bukkit.jar//io.github.kosmx.emotes.bukkit.network.BukkitNetworkInstance.sendMessage(BukkitNetworkInstance.java:42)
> [11:55:49 WARN]:        at emotecraft-2.2.5-bukkit.jar//io.github.kosmx.emotes.api.proxy.AbstractNetworkInstance.sendMessage(AbstractNetworkInstance.java:54)
> [11:55:49 WARN]:        at emotecraft-2.2.5-bukkit.jar//io.github.kosmx.emotes.api.proxy.AbstractNetworkInstance.sendMessage(AbstractNetworkInstance.java:72)
> [11:55:49 WARN]:        at emotecraft-2.2.5-bukkit.jar//io.github.kosmx.emotes.server.network.IServerNetworkInstance.presenceResponse(IServerNetworkInstance.java:30)
> [11:55:49 WARN]:        at emotecraft-2.2.5-bukkit.jar//io.github.kosmx.emotes.bukkit.network.BukkitNetworkInstance.presenceResponse(BukkitNetworkInstance.java:52)
> [11:55:49 WARN]:        at emotecraft-2.2.5-bukkit.jar//io.github.kosmx.emotes.server.network.AbstractServerEmotePlay.receiveMessage(AbstractServerEmotePlay.java:103)
> [11:55:49 WARN]:        at emotecraft-2.2.5-bukkit.jar//io.github.kosmx.emotes.server.network.AbstractServerEmotePlay.receiveMessage(AbstractServerEmotePlay.java:92)
> [11:55:49 WARN]:        at emotecraft-2.2.5-bukkit.jar//io.github.kosmx.emotes.bukkit.network.ServerSideEmotePlay.receivePluginMessage(ServerSideEmotePlay.java:45)
> [11:55:49 WARN]:        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
> [11:55:49 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3543)
> [11:55:49 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInCustomPayload.a(PacketPlayInCustomPayload.java:37)
> [11:55:49 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInCustomPayload.a(PacketPlayInCustomPayload.java:15)
> [11:55:49 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
> [11:55:49 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
> [11:55:49 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
> [11:55:49 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
> [11:55:49 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
> [11:55:49 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
> [11:55:49 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
> [11:55:49 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
> [11:55:49 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
> [11:55:49 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
> [11:55:49 WARN]:        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1289)
> [11:55:49 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1177)
> [11:55:49 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
> [11:55:49 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
> ```

the same error occurs on Purpur 1.18.2...

**Comment by djohts** [comment]
> I have same issue, but other error.
> 
> 1.19.3 Paper Server
> 
> ```
> [11:55:49 WARN]: org.bukkit.plugin.messaging.MessageTooLargeException: Attempted to send a plugin message that was too large. The maximum length a plugin message may be is 32766 bytes (tried to send one that is 48602 bytes long).
> [11:55:49 WARN]:        at org.bukkit.plugin.messaging.StandardMessenger.validatePluginMessage(StandardMessenger.java:547)
> [11:55:49 WARN]:        at org.bukkit.craftbukkit.v1_19_R2.entity.CraftPlayer.sendPluginMessage(CraftPlayer.java:1996)
> [11:55:49 WARN]:        at emotecraft-2.2.5-bukkit.jar//io.github.kosmx.emotes.bukkit.network.BukkitNetworkInstance.sendMessage(BukkitNetworkInstance.java:42)
> [11:55:49 WARN]:        at emotecraft-2.2.5-bukkit.jar//io.github.kosmx.emotes.api.proxy.AbstractNetworkInstance.sendMessage(AbstractNetworkInstance.java:54)
> [11:55:49 WARN]:        at emotecraft-2.2.5-bukkit.jar//io.github.kosmx.emotes.api.proxy.AbstractNetworkInstance.sendMessage(AbstractNetworkInstance.java:72)
> [11:55:49 WARN]:        at emotecraft-2.2.5-bukkit.jar//io.github.kosmx.emotes.server.network.IServerNetworkInstance.presenceResponse(IServerNetworkInstance.java:30)
> [11:55:49 WARN]:        at emotecraft-2.2.5-bukkit.jar//io.github.kosmx.emotes.bukkit.network.BukkitNetworkInstance.presenceResponse(BukkitNetworkInstance.java:52)
> [11:55:49 WARN]:        at emotecraft-2.2.5-bukkit.jar//io.github.kosmx.emotes.server.network.AbstractServerEmotePlay.receiveMessage(AbstractServerEmotePlay.java:103)
> [11:55:49 WARN]:        at emotecraft-2.2.5-bukkit.jar//io.github.kosmx.emotes.server.network.AbstractServerEmotePlay.receiveMessage(AbstractServerEmotePlay.java:92)
> [11:55:49 WARN]:        at emotecraft-2.2.5-bukkit.jar//io.github.kosmx.emotes.bukkit.network.ServerSideEmotePlay.receivePluginMessage(ServerSideEmotePlay.java:45)
> [11:55:49 WARN]:        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455)
> [11:55:49 WARN]:        at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:3543)
> [11:55:49 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInCustomPayload.a(PacketPlayInCustomPayload.java:37)
> [11:55:49 WARN]:        at net.minecraft.network.protocol.game.PacketPlayInCustomPayload.a(PacketPlayInCustomPayload.java:15)
> [11:55:49 WARN]:        at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$ensureRunningOnSameThread$1(PlayerConnectionUtils.java:51)
> [11:55:49 WARN]:        at net.minecraft.server.TickTask.run(TickTask.java:18)
> [11:55:49 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.d(IAsyncTaskHandler.java:153)
> [11:55:49 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(IAsyncTaskHandlerReentrant.java:24)
> [11:55:49 WARN]:        at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1341)
> [11:55:49 WARN]:        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197)
> [11:55:49 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.x(IAsyncTaskHandler.java:126)
> [11:55:49 WARN]:        at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1318)
> [11:55:49 WARN]:        at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1311)
> [11:55:49 WARN]:        at net.minecraft.util.thread.IAsyncTaskHandler.c(IAsyncTaskHandler.java:136)
> [11:55:49 WARN]:        at net.minecraft.server.MinecraftServer.i_(MinecraftServer.java:1289)
> [11:55:49 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1177)
> [11:55:49 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
> [11:55:49 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
> ```

same on git-Purpur-1985 (MC: 1.19.4)
