### ISSUE TITLE
Could not pass event EntityPoseChangeEvent to emotecraft v2.2.5

### ISSUE THREAD

**Issue by Danila767** [KosmX/emotes#339]
Pufferfish 1.19.2 build 47

```
[18:21:01 ERROR]: Could not pass event EntityPoseChangeEvent to emotecraft v2.2.5
java.lang.NullPointerException: Cannot invoke "io.github.kosmx.emotes.server.network.IServerNetworkInstance.getEmoteTracker()" because the return value of "io.github.kosmx.emotes.server.network.AbstractServerEmotePlay.getPlayerNetworkInstance(Object)" is null
        at io.github.kosmx.emotes.server.network.AbstractServerEmotePlay.playerEntersInvalidPose(AbstractServerEmotePlay.java:195) ~[emotecraft-2.2.5-bukkit.jar:?]
        at io.github.kosmx.emotes.bukkit.network.ServerSideEmotePlay.playerDies(ServerSideEmotePlay.java:155) ~[emotecraft-2.2.5-bukkit.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor307.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:git-Pufferfish-47]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.Entity.setPose(Entity.java:714) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
        at net.minecraft.world.entity.player.Player.updatePlayerPose(Player.java:430) ~[?:?]
        at net.minecraft.world.entity.player.Player.tick(Player.java:323) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:688) ~[?:?]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:630) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
        at net.minecraft.server.players.PlayerList.remove(PlayerList.java:612) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2128) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2108) ~[?:?]
        at net.minecraft.network.Connection.handleDisconnection(Connection.java:776) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:253) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:449) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1399) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1175) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:307) ~[pufferfish-1.19.2.jar:git-Pufferfish-47]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by KosmX** [comment]
Please provide **full** log file.

**Comment by ZodionMC** [comment]
[latest.log](https://github.com/KosmX/emotes/files/11477544/latest.log)
Pasting a log file from my own server. In this case the error happened after a fresh boot, immediately after a player logged in.
