### ISSUE TITLE
In the console of my server, an error pops up with EmoteCraft, which is very annoying and I would like to get rid of it, but I don’t understand anything about it, help

### ISSUE THREAD

**Issue by mawerss** [KosmX/emotes#351]
Here is the text of the entire error:

[16:55:44 ERROR]: Could not pass event EntityPoseChangeEvent to emotecraft v2.2.0
[16:55:44 ERROR]: Suspected Plugins: 
[16:55:44 ERROR]:       emotecraft{enabled,ver=2.2.0,path=plugins/emotecraft-2.2.0-bukkit.jar}
[16:55:44 ERROR]: Exception details below: 
java.lang.NullPointerException: Cannot invoke "io.github.kosmx.emotes.server.network.IServerNetworkInstance.getEmoteTracker()" because the return value of "io.github.kosmx.emotes.server.network.AbstractServerEmotePlay.getPlayerNetworkInstance(Object)" is null
        at io.github.kosmx.emotes.server.network.AbstractServerEmotePlay.playerEntersInvalidPose(AbstractServerEmotePlay.java:195) ~[emotecraft-2.2.0-bukkit.jar:?]
        at io.github.kosmx.emotes.bukkit.network.ServerSideEmotePlay.playerDies(ServerSideEmotePlay.java:155) ~[emotecraft-2.2.0-bukkit.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor415.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[patina-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patina-api-1.19.2-R0.1-SNAPSHOT.jar:git-Paper-"88b8e3f"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patina-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:684) ~[patina-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.entity.Entity.setPose(Entity.java:714) ~[patina-1.19.2.jar:git-Paper-"88b8e3f"]
        at net.minecraft.world.entity.player.Player.updatePlayerPose(Player.java:430) ~[?:?]
        at net.minecraft.world.entity.player.Player.tick(Player.java:323) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:688) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.tick(ServerGamePacketListenerImpl.java:366) ~[?:?]
        at net.minecraft.network.Connection.tick(Connection.java:588) ~[?:?]
        at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:233) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1575) ~[patina-1.19.2.jar:git-Paper-"88b8e3f"]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:458) ~[patina-1.19.2.jar:git-Paper-"88b8e3f"]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1407) ~[patina-1.19.2.jar:git-Paper-"88b8e3f"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1177) ~[patina-1.19.2.jar:git-Paper-"88b8e3f"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:308) ~[patina-1.19.2.jar:git-Paper-"88b8e3f"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by KosmX** [comment]
Please share full logs, not just parts.  
This report is invalid as I can not help without enough information.

**Comment by KosmX** [comment]
Also, please update the plugin
