### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by foxya27** [KosmX/emotes#394]
[23:41:29 ERROR]: Could not pass event EntityPoseChangeEvent to emotecraft v2.2.0
java.lang.NullPointerException: Cannot invoke "io.github.kosmx.emotes.server.network.IServerNetworkInstance.getEmoteTracker()" because the return value of "io.github.kosmx.emotes.server.network.AbstractServerEmotePlay.getPlayerNetworkInstance(Object)" is null
at io.github.kosmx.emotes.server.network.AbstractServerEmotePlay.playerEntersInvalidPose(AbstractServerEmotePlay.java:195) ~[emotecraft-2.2.0-bukkit.jar:?]
at io.github.kosmx.emotes.bukkit.network.ServerSideEmotePlay.playerDies(ServerSideEmotePlay.java:155) ~[emotecraft-2.2.0-bukkit.jar:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor180.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2004]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2004]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2004]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
at net.minecraft.world.entity.Entity.setPose(Entity.java:757) ~[purpur-1.20.1.jar:git-Purpur-2004]
at net.minecraft.world.entity.player.Player.updatePlayerPose(Player.java:467) ~[?:?]
at net.minecraft.world.entity.player.Player.tick(Player.java:350) ~[?:?]
at net.minecraft.server.level.ServerPlayer.doTick(ServerPlayer.java:779) ~[?:?]
at net.minecraft.server.players.PlayerList.remove(PlayerList.java:604) ~[purpur-1.20.1.jar:git-Purpur-2004]
at net.minecraft.server.players.PlayerList.remove(PlayerList.java:585) ~[purpur-1.20.1.jar:git-Purpur-2004]
at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2216) ~[?:?]
at net.minecraft.server.network.ServerGamePacketListenerImpl.onDisconnect(ServerGamePacketListenerImpl.java:2195) ~[?:?]
at net.minecraft.network.Connection.handleDisconnection(Connection.java:827) ~[?:?]
at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:254) ~[?:?]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1614) ~[purpur-1.20.1.jar:git-Purpur-2004]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.1.jar:git-Purpur-2004]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1421) ~[purpur-1.20.1.jar:git-Purpur-2004]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[purpur-1.20.1.jar:git-Purpur-2004]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2004]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by KosmX** [comment]
What is the real issue?  
full server logs?

**Comment by dima-dencep** [comment]
in 1.21.4 this event is no longer used
