### ISSUE TITLE
[CRASH] Level Text Fix

### ISSUE THREAD

**Issue by nco2k** [KosmX/emotes#479]
game not starting with following mods installed:

- emotecraft-for-MC1.20.4-2.4.0-a.f140890e-fabric.jar
- LevelTextFix-Fabric-1.20.4-10.0.3.jar
- fabric-api-0.97.0+1.20.4.jar (2.09 MiB) Primary

response from the [LevelTextFix](https://github.com/Darkhax-Minecraft/Level-Text-Fix/issues/3) dev:

> This looks like an issue with Emotecraft loading classes too early. Could you please report this issue on their page.

**CRASH LOG**

> Uncaught exception in thread "main"
> java.lang.RuntimeException: Mixin transformation of net.minecraft.client.main.Main failed
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:463)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [leveltextfix.mixins.json:MixinComponent from mod leveltextfix] from phase [DEFAULT] in config [leveltextfix.mixins.json] FAILED during PREPARE
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinPrepareError(MixinProcessor.java:585)
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:543)
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462)
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438)
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290)
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
> 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
> 	... 7 more
> Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTargetAlreadyLoadedException: Critical problem: leveltextfix.mixins.json:MixinComponent from mod leveltextfix target net.minecraft.class_2561 was loaded too early.
> 	at org.spongepowered.asm.mixin.transformer.MixinInfo.readDeclaredTargets(MixinInfo.java:948)
> 	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:882)
> 	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852)
> 	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:781)
> 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540)
> 	... 13 more

**Comment by dima-dencep** [comment]
It was fixed in 1.21.4, I will do a backport to 1.21.1 soon
